# Paths here are relative to the root folder of the project

paths:
  data_dir: "data"
  descriptions_file: "doc_types - real_labels - splits/doc_type_desc_sample_10types.json"
  output_dir: "outputs"

types:
  ["maintenance_training_summary", "incident_report"] # Example

k: # Not implemented yet
  10